# Generated by Django 4.1.4 on 2022-12-23 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_userprofile_profile_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='facebook_link',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='twitter_link',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='youtube_link',
        ),
    ]
